### ISSUE TITLE
OCSP stapling

### ISSUE THREAD

**Issue by lukytux** [EthACKdotOrg/ssl-checker#5]
La détection de l'OCSP stapling fonctionne mais le résultat dans le .json est toujours négatifs;

sslyze output;

 * Certificate - OCSP Stapling:
      OCSP Response Status:              successful
      Validation w/ Mozilla's CA Store:  OK - Response is trusted
      Responder Id:                      FA58DB0953BC19C5E7B58BF610F81E846D3A8FD8
      Cert Status:                       good
      Cert Serial Number:                49DA
      This Update:                       Feb 20 05:02:38 2015 GMT
      Next Update:                       Feb 27 05:02:38 2015 GMT

json;
 "ocsp_stapling": 0,

**Comment by cjeanneret** [comment]
Pouvez-vous mettre le bout de JSON généré via la sortie de SSLyze? le check se fait sur un point précis de la sortie de SSLyze, peut-être que c'est passé à côté (pourtant testé).
